language: java
sudo: false
jdk:
- oraclejdk8
env:
  global:
  - DISPLAY=:99.0
cache:
  directories:
  - "$HOME/.m2"
  - '$HOME/.sonar/cache'
git:
  submodules: false
addons:
  sonarqube:
    token:
      secure: OavSbNL8H4I/+A3c/KOa0LRdn3dffjOQAaMu1Hsc4t2AxW/HQDv9hjfU/O2CHFaLRO09HB96cBBdd6AbY9a9aXtplTyWL5qbciLbeLwp8C8j6aeSuLRebDvXUMbY4WGcNAt7OJ8wk0+d80JZ61r4mkGbTmbH0xMvVn9+s19cPn4bnW0J1Si4km68NfdW2LaJTkPIsql+QYk+fNReILGUldj3BOrwC5jOkxH8NQZQM17kdeMhgLv9bGNG87bCAWW8w5lPvvwhjwriiUFh6aTt629BZZygP4pOSCgJ1PP8noyde5zlwpPY6SQ3KRqa71My2k+LXs0H4O/fiVre7ytT780kfZHXdxkPUmqFGEUYY3ZpPQ/betiegm098gnPpaOn/9rxfhc7llO3+UctONR5NUn7MNg8bj8llOE+bMwliJoSSu70B7MkEBbSDE5pIPbofoP3WwtlIhOiEehdcWV1VFDrnX4fKJBNL55rOxIgucWrxzL22FdizptyLuBr5U3NtppOS93VJcVujAdKngd3Zdpp1xcpx3wg4D88OPRbKaPo/jyeNbZmQglZeoATFp95mK1OhGxw1CFCD4sF9wnCQbtlQGK42s7QnNEhk0qfXaCJNFLT+QChPPpzK934Gq/9B2RGYi6aUUPMItuINqrK3+TcEQrrzv7AGm6pZajBu0Y=
before_install:
- sh -e /etc/init.d/xvfb start - sleep 10
- git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
- ". /tmp/BuildUtilities/travis-ci/installMaven.sh"
install: true
script:
- mvn clean install
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar
after_success:
- ". /tmp/BuildUtilities/travis-ci/deploy.sh framework releng/tools.vitruv.updatesite.aggregated
  final vitruv-tools updatesite"
