language: java
sudo: false
jdk:
- oraclejdk8
env:
  global:
  - DISPLAY=:99.0
  - secure: cTmtYH0TGwhXjLD4TR+6/aL09/4dNtk/nnMzLXslYIjT4mXH6QUOu2w0RpywyhxGBbtMXpGLhA0fMX6f7IEHHiTCjXQllbVr6gV1mSEE1rFtgMJ91uNFwcRDK3KyCxGwALdIrwCK5g/bbZ7I6mRAwDuROP3BfLGo6u+bhX6Vb24rlOcigHHkecgUEyk5islSjpuZiOtE3BG76+6TlKAg1BWnvWvGQ9b+0opxYtZYqVDcZsz2TNLrp9kKHl9Bb0XQ/MCBvcVPvo3XSvCNduTPKhms/5+OX33JAFtdWcD2kYsNabSZHzvO0COXhzmMV9xe1k/KDDF5UEcwc1WSaHs9GnqkVWhy3LmJHJJ2O6eUTQdiDLypFRfwKsKcJMG2Bv82/E3rpgFFdvF+hVmQktTJhPO6MH1CG5O04WW1JBlEvfLrTsOgyTVX7lOY5ayXbLfmtx0fHzkkf/+Cus9GECFym5N/byZXO+55OWocU9p07P7xFZZnK6sP9KNhznLMRJqP0E2iwABHOfbHrUorInlIn+jwK4O7cl7Zo3O4yKuZtLD1ALd5dtBge6mlFgiV2xoPh1qTJtDz9Yf1DYypGmxLi9qGuhQCaAlX/WH9hFu9yLCPtp2P9nUaxAeseI1jDE1Av0x69xFWZA8VDcyuVW/Qqu4pBkcBFsHQrgQ3j2Ns96g=
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
git:
  submodules: false
before_install:
- sh -e /etc/init.d/xvfb start - sleep 10
- git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
- ". /tmp/BuildUtilities/travis-ci/installMaven.sh"
- echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
install: true
script:
- mvn clean install -Pprocess-xtend-code
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
after_success:
- ". /tmp/BuildUtilities/travis-ci/deploy.sh framework releng/tools.vitruv.updatesite.aggregated
  final vitruv-tools updatesite"
