language: java
sudo: false
jdk:
- oraclejdk8
env:
  global:
  - DISPLAY=:99.0
    secure: "E150snlbaFdovUX2+8X6Z9GDeskMqW4QHeCfvQIn2QsSsqB1iXr2NH1pI5c63zSQBjwTTgpBlwh/xWBj7KZ3/mK/ArHuyfn7bqOHZaeWvOANPDMj+HLp5+nJJJTmatlQh4Io0NUNdz6O4HyIi+O2nfRUQDCMK/1qIFUZ+c/S1v0x9N3A8e6igjguKrMx5CcdVQ42RbORShGzHYdESmuc9gDjI7+Eq9kRKKlOktBh+mIzM6S7CfAoCS1asbJwJREzi7ngvA8hWK3pKSkO9MGs+Tc4/XfzdnVK1K0KRAdAfXmv3B4QDqecDlXbiDzA9E3a325R18hzlUdc9r4T/V/hUxA9J7XdbQuq1CTmIG5GAtHHeLoz+3QcjKu8cwi8ivxCq5VyYNR+6aLhGp/bMzlOXMNNPY/OUV0HeAaaXgrHwlq+d9yIgycP6bnIcwJIfjD3JcsaRsBGdV5PlMieQuVeO6B3JTK7vFRBYeQew4n5/6IMaBI7MNZk1edu3QZUXVQuKf9a50nRiKcog71cAKG3Zv47VBfkL+oJOMWNtTw4Ityfado9KE66u1eo1CvsTXWfPGHoNgGyKrGuP4/gpF7mLpIObDut2q1U0ldCWXDKB7E4TG7K7OcHsVQ3s+aRLul8MDoBntkdnU0TSN4m8P/fSxWyXpJfxbuFvB8/+yoGABU="
cache:
  directories:
  - "$HOME/.m2"
  - '$HOME/.sonar/cache'
git:
  submodules: false
before_install:
- sh -e /etc/init.d/xvfb start - sleep 10
- git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
- ". /tmp/BuildUtilities/travis-ci/installMaven.sh"
install: true
script:
- mvn clean install
- mvn sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
after_success:
- ". /tmp/BuildUtilities/travis-ci/deploy.sh framework releng/tools.vitruv.updatesite.aggregated
  final vitruv-tools updatesite"
