/*
 * generated by Xtext
 */
package edu.kit.ipd.sdq.xocl4inv.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XOcl4InvUiModule extends edu.kit.ipd.sdq.xocl4inv.ui.AbstractXOcl4InvUiModule {
	public XOcl4InvUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
