/*
 * generated by Xtext
 */
package edu.kit.ipd.sdq.xocl4inv.ui.contentassist

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XOcl4InvProposalProvider extends AbstractXOcl4InvProposalProvider {
}
