platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.3.9-jdk-8

inputs:
  - name: vitruv-git-repo

run:
  path: mvn
  args: ["-f", "vitruv-git-repo/pom.xml", "clean", "install"]

params:
  MAVEN_BASEDIR: vitruv-git-repo
