platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.3.9-jdk-8

inputs:
  - name: vitruv-git-repo

run:
  path: sh
  args:
  - -exc
  - |
    apt-get update
    apt-get install -y xvfb
    export DISPLAY=:99
    sh -e /etc/init.d/xvfb start - sleep 10
    mvn -f vitruv-git-repo/pom.xml clean install

params:
  MAVEN_BASEDIR: vitruv-git-repo
