platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.3.9-jdk-8

inputs:
  - name: vitruv-git-repo

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    find .

params:
  MAVEN_BASEDIR: vitruv-git-repo
